### ISSUE TITLE
What is licence of the splade/sparsembed models hosted in huggingface?

### ISSUE THREAD

**Issue by seganrasan** [raphaelsty/neural-cherche#10]
Hi @raphaelsty, could you please let me know what is the licence of the below splade/sparsembed models hosted in huggingface?

https://huggingface.co/raphaelsty/splade-max
https://huggingface.co/raphaelsty/distilbert-splade
https://huggingface.co/raphaelsty/sparsembed-max
https://huggingface.co/raphaelsty/distilbert-sparsembed

**Comment by raphaelsty** [comment]
Sparsembed models are fully open-source. 

I'm not sure for Splade since the original work is not open-source. I did create the code from scratch and did not reuse any code or weights from the original paper. On my side I put an MIT License on the repository. So I don't know if authors license apply or not to the specific Splade model.

**Comment by skeptrunedev** [comment]
I had the exact same question, it might be a good idea to put that in the README

**Comment by seganrasan** [comment]
+1. It would be great if you update the licence info in the huggingface page especially for 

https://huggingface.co/raphaelsty/sparsembed-max
https://huggingface.co/raphaelsty/splade-max

**Comment by raphaelsty** [comment]
@seganrasan SparseEmbed is open-source, 

I don't know about splade-max which I think is non-commercial only even if I wrote a brand new code and train a model with my code code.

**Comment by seganrasan** [comment]
Thanks @raphaelsty. It would be really helpful if you update the licence details of SparseEmbed model in the huggingface page.  https://huggingface.co/raphaelsty/sparsembed-max

**Comment by raphaelsty** [comment]
Updated the Readme and the HuggingFace models checkpoints

**Comment by seganrasan** [comment]
thanks @raphaelsty
