### ISSUE TITLE
Bug in the utils/evaluate.py file

### ISSUE THREAD

**Issue by Yu-Zhou** [raphaelsty/neural-cherche#34]
First, thanks very much for creating this package, it has been really useful!

When I used the latest version, I found an error. Note the call's arguments is 
`add_duplicates(queries=queries, results=scores)`,
while the method definition is 
`add_duplicates(queries: list[str], scores: list[list[dict]])`

https://github.com/raphaelsty/neural-cherche/blob/e0e75f989bdab92c6b51f7c4af4e6f7f684adc49/neural_cherche/utils/evaluate.py#L201

**Comment by raphaelsty** [comment]
Hi @Yu-Zhou , thank you for your feedback ! 

Which version of neural-cherche are you using ? 

Could you try installing neural-cherche latest version ? 

```bash
pip install "neural_cherche[eval]"==1.4.3
```

Here is a sample script to run evaluation and it run fine with the last version, BM25 and scifact dataset:

```python
from neural_cherche import models, retrieve, utils

documents, queries, qrels = utils.load_beir(
    "scifact",
    split="test",
)

retriever = retrieve.BM25(
    key="id",
    on=["title", "text"],
)

documents_embeddings = retriever.encode_documents(
    documents=documents,
)

retriever = retriever.add(documents_embeddings=documents_embeddings)


queries_embeddings = retriever.encode_queries(
    queries=queries,
)

scores = retriever(
    queries_embeddings=queries_embeddings,
    k=10,
    tqdm_bar=True,
    batch_size=1024,
)

scores = utils.evaluate(
    scores=scores,
    qrels=qrels,
    queries=queries,
    metrics=["ndcg@10"] + [f"hits@{k}" for k in range(1, 10)],
)

print(scores)
```

**Comment by Yu-Zhou** [comment]
Hi @raphaelsty , thanks very much, the issue is gone after using the latest version. Have tested your example, and also a bigger example in my environment.
